# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8b2a686418652eae69e3fa6fe1f5b01"
name = "Tailor size guide"
application_url = "https://size-guide.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled" 

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"


[auth]
redirect_urls = [
  "https://size-guide.fly.dev/auth/callback",
  "https://size-guide.fly.dev/auth/shopify/callback",
  "https://size-guide.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://size-guide.fly.dev"
subpath = "size-guide"
prefix = "apps"
